---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
# this is not called yet, uncomment in default-pipeline.yml to trigger the pipeline
steps:
  - label: "Build"
    command: "true"

  - label: "Test"
    command: "true"

  - label: "Deploy"
    command: "true"

  - label: "Publish"
    command: "true"
