import fs from 'fs';
import cliProgress from 'cli-progress';
import { log } from '../utils/logger.ts';
import type { IdentityPool } from './identity_pool.ts';
import type { EntityIdentity } from './identity_pool.ts';
import {
  getRiskEnginePerfScenarioDir,
  getRiskEnginePerfScenarioEntitiesPath,
} from '../utils/data_paths.ts';

export interface EntityStoreDataParams {
  name: string;
  pool: IdentityPool;
}

/**
 * Entity documents follow the nested `Entity` shape from Kibana entity_store
 * (`common/domain/definitions/entity.gen.ts`): `entity.id`, `entity.name`, `entity.type`,
 * `entity.lifecycle`, optional `entity.relationships.resolution.resolved_to`, plus
 * `user` / `host` identity blocks (not flat `user.name` top-level keys).
 */
const buildEntityDocument = (identity: EntityIdentity, ts: string): Record<string, unknown> => {
  const entity: Record<string, unknown> = {
    id: identity.entityId,
    name: identity.name,
    type: identity.type,
    lifecycle: {
      first_seen: ts,
      last_seen: ts,
    },
  };

  if (identity.resolvedTo) {
    entity.relationships = {
      resolution: {
        resolved_to: identity.resolvedTo,
      },
    };
  }

  if (identity.type === 'user') {
    const hostId = identity.pairedHostId ?? identity.name;
    return {
      '@timestamp': ts,
      entity,
      user: {
        name: identity.name,
      },
      host: {
        id: hostId,
      },
      event: {
        kind: 'event',
        category: ['network'],
        outcome: 'success',
        module: 'local',
      },
    };
  }

  return {
    '@timestamp': ts,
    entity,
    host: {
      name: identity.name,
      // Explicit host.id so the EUID formula uses the host.id branch,
      // matching the host alerts generated by generate_scenario_data.ts.
      id: identity.name,
    },
  };
};

export const generateEntityStoreData = async (params: EntityStoreDataParams): Promise<void> => {
  const { name, pool } = params;
  const outPath = getRiskEnginePerfScenarioEntitiesPath(name);
  const scenarioDir = getRiskEnginePerfScenarioDir(name);
  if (!fs.existsSync(scenarioDir)) {
    fs.mkdirSync(scenarioDir, { recursive: true });
  }
  if (fs.existsSync(outPath)) {
    fs.unlinkSync(outPath);
  }

  const all = pool.all;
  log.info(`Writing ${all.length} entity documents to ${outPath}`);

  const progress = new cliProgress.SingleBar(
    {
      clearOnComplete: false,
      hideCursor: true,
      format: 'entities {bar} {value}/{total}',
    },
    cliProgress.Presets.shades_classic,
  );
  progress.start(all.length, 0);

  const stream = fs.createWriteStream(outPath, { flags: 'a' });
  const ts = new Date().toISOString();

  for (const identity of all) {
    const doc = buildEntityDocument(identity, ts);
    stream.write(JSON.stringify(doc) + '\n');
    progress.increment();
  }

  await new Promise<void>((resolve, reject) => {
    stream.end((err?: Error | null) => (err ? reject(err) : resolve()));
  });
  progress.stop();
  log.info(`Wrote entity store file ${outPath}`);
};
